### PR TITLE
Use DSSet parameter to get channel info instead of radiotap header

### PR DESCRIPTION
**Pull request by solsticedhiver**
I am not exactly sure about this DSset parameter but it seems to hold the channel used by the AP.

Might be more reliable than the radiotap header if the driver is buggy (?)

### CODE REVIEW

**Comment by lukius** [comment]
The _DS Parameter Set_ information element seems to be only valid when direct-sequence spread spectrum (DSSS) modulation is used. In newer 802.11 protocols with e.g. OFDM modulation this fix will probably not work. However, it might still be possible to use the first channel finding method and, should it fail, fall back to this one as a last resort. The code to do this should be rather straightforward as it simply combines both approaches.

**Review by lukius — CHANGES_REQUESTED** [review]
Looks good, but please see my comment in the Conversation tab.

**Comment by solsticedhiver** [comment]
There were 2 problems here.
1. The radiotap header was not parsed correctly (for some reason)
2. The frequency in the radiotap header was not correct.

I made a simple fix for problem #1 by using a fixed offset in the notdecoded scapy code.
This needs a more reliable way to be parsed and to get the frequency from radiotap header. And a more general approach is to use the **radiotap** module form _python-radiotap_ (or backport their code).

I don't know the cause of problem #2. Moreover, it is now gone, so I can't pinpoint the cause. May be some libpcap bug ? or scapy ?
So my use of DSset was a quick fix for all this.

From my understanding OFDM is not new and was already used in wifi 802.11 g (?). And DSset parameter is still there. I didn't find much documentation about that parameter but it holds the channel used by the BSSID.

So I let you use the radiotap module to parse the radiotap headers and close my PR for that DSset parameter we don't know much about.

**Comment by lukius** [comment]
Thanks for your feedback. 

#1 may be due to the attack being developed just for 2.4 GHz frequency ranges (see [here](https://github.com/lukius/wifi-deauth/blob/716b276039409f4f944efc19553d7507c3250985/attack/utils.py#L68)). As for your last comment about #2, one plausible explanation is a change in the modulation used by the protocol. DSSS might have been used on your first try where the _DS Parameter Set_ information element is valid and holds the channel, as you pointed out. On the other hand, another modulation scheme might have been used later and thus that value would be no longer valid.

For further information on 802.11 information elements, see [here](https://www.safaribooksonline.com/library/view/80211-wireless-networks/0596100523/ch04.html).

**Pull request closed without merging**
